baseURL = "http://kimmj.github.io/"
languageCode = "en-us"
title = "Ibiza"


theme = [ "mj-custom-theme", "hugo-theme-learn" ]

[markup.goldmark.renderer]
unsafe= true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
  # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page. 
  # Useful to give opportunity to people to create merge request for your doc.
  # See the config.toml file from this documentation site to have an example.
  editURL = ""
  # Author of the site, will be used in meta information
  author = "Myeongjin Kim"
  # Description of the site, will be used in meta information
  description = "Do Learn"
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = false
  # Disable search function. It will hide search bar
  disableSearch = false
  # Javascript and CSS cache are automatically busted when new version of site is generated. 
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false
  # A title for shortcuts in menu is set by default. Set this to true to disable it. 
  disableShortcutsTitle = false
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = false
  # Hide breadcrumbs in the header and only show the current page title
  disableBreadcrumb = false
  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev = true
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "mine"

[[menu.shortcuts]] 
name = "<i class='fab fa-github'></i> Github"
identifier = "ds"
url = "https://github.com/KimMJ"
weight = 10

# [[menu.shortcuts]]
# name = "<i class='fas fa-camera'></i> Showcases"
# url = "/showcase"
# weight = 11

[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> Hugo Documentation"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> Hugo Theme Learn"
identifier = "hugo-theme-learn"
url = "https://learn.netlify.com/en/"
weight = 20


# [[menu.shortcuts]]
# name = "<i class='fas fa-bullhorn'></i> Credits"
# url = "/credits"
# weight = 30

[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"
weight = 30

# # English is the default language
# defaultContentLanguage = "ko"
# # Force to have /en/my-page and /fr/my-page routes, even for default language.
# defaultContentLanguageInSubdir = false

# [Languages]
# [Languages.en]
# title = "Documentation for Hugo Learn Theme"
# weight = 2
# languageName = "English"

# [Languages.kr]
# title = "Hugo Learn의 문서"
# weight = 1
# languageName = "Korean"
